export enum EnvironmentEnum {
  DB_PATH = 'DB_PATH',
  BIND_HOST = 'BIND_HOST',
  FE_PATH = 'FE_PATH',
  DOWNLOADS_PATH = 'DOWNLOADS_PATH',
  FORMAT = 'FORMAT',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_HOST = 'REDIS_HOST',
  REDIS_RUN = 'REDIS_RUN',
  DOWNLOAD_CONCURRENCY = 'DOWNLOAD_CONCURRENCY',
  DOWNLOAD_GAP_MS = 'DOWNLOAD_GAP_MS',
  SEARCH_CONCURRENCY = 'SEARCH_CONCURRENCY',
  STATIC_PLAYLISTS_PATH = 'STATIC_PLAYLISTS_PATH',
}
