"""Shared medley test fixtures. The JSON fixtures are regenerated by fixtures/make_fixtures.py;
tests get fresh copies of anything they may mutate. `import synth` works in every medley test
(fixtures/ is put on sys.path here)."""

import copy
import json
import os
import sys

import pytest

FIX = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fixtures")
if FIX not in sys.path:
    sys.path.insert(0, FIX)

from automix.medley import schema as S  # noqa: E402

FEATS_NAMES = ("dance_no_more", "dreaming", "bluebird")
_cache: dict = {}


def load_fixture(name: str):
    """Parsed JSON fixture (a deep copy, safe to mutate)."""
    if name not in _cache:
        with open(os.path.join(FIX, name)) as fh:
            _cache[name] = json.load(fh)
    return copy.deepcopy(_cache[name])


@pytest.fixture
def comp() -> dict:
    """DESIGN §8.10 j01 drop_swap, Dance No More -> Dreaming (lock, ramp, pulsed lead)."""
    return load_fixture("comp_drop_swap.json")


@pytest.fixture
def comp_slam() -> dict:
    """j02 roll_slam, Dreaming -> Bluebird (free, roll + vacuum, tempo step at m = 0)."""
    return load_fixture("comp_roll_slam.json")


@pytest.fixture(scope="session")
def feats() -> dict:
    """{"dance_no_more" | "dreaming" | "bluebird": Feats}; do not mutate (session scope)."""
    return {n: load_fixture(f"feats_{n}.json") for n in FEATS_NAMES}


@pytest.fixture
def program() -> "S.Program":
    """The §12 Program compiled from comp_drop_swap.json."""
    with open(os.path.join(FIX, "program_drop_swap.json")) as fh:
        return S.from_json(fh.read(), S.Program)


@pytest.fixture
def plan() -> dict:
    """A two-song SessionPlanMedley around j01 (composition included)."""
    return load_fixture("plan_drop_swap.json")


@pytest.fixture(scope="session")
def synth():
    import synth as mod
    return mod


@pytest.fixture
def rehash():
    """rehash(comp) -> comp with its hash recomputed (after a deliberate mutation)."""
    def _rehash(c: dict) -> dict:
        c["hash"] = S.canonical_hash(c)
        return c
    return _rehash
